---
driver_plugin: vagrant

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
    run_list:
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[confluence]
    attributes: {
      "java": {
        "jdk_version": 7
      }
    }
  - name: nginx_proxy
    run_list:
      - recipe[confluence::proxy]
    attributes: {}
  - name: confluence-db
    run_list:
      - recipe[confluence::database]
    attributes: {
      "postgresql": {
        "password": {
          "postgres": "postgres"
        }
      }
    }
